// Names the objects on each theme asset sheet for scripts/extract-theme-assets.mjs. `at` is a
// point inside the object (or several points, when one asset is made of loose pieces); `cuts`
// are lines that separate objects touching on the sheet; `skip` marks painted groups that are
// deliberately not exported. Coordinates are pixels on the 1672×941 sheets.
export const THEME_ASSETS = {
  garden: {
    title: 'Garden',
    sheet: 'garden-assets.png',
    dir: 'garden',
    // Tight grouping: the tree canopy sits only a few pixels below the long canopy branch.
    groupDistance: 4,
    cuts: [
      // Round the cottage spire, which pokes up into the grass at the foot of the tree.
      [630, 843, 694, 843], [694, 843, 694, 818], [694, 818, 726, 818], [726, 818, 726, 843], [726, 843, 800, 843],
      // Between two fireflies whose glows overlap.
      [1405, 909, 1449, 865]
    ],
    assets: [
      { name: 'tree-light', at: [700, 600], mode: 'Light', signature: 'tree-light.png', role: 'Primary right-edge anchor: trunk, roots and flowering crown, with toadstools on the bark. No cottage painted in', motion: 'None (the trunk stays rooted); animate the separate branches and leaves around it', mobile: 'Keep, crop strategically to the trunk and lower crown' },
      { name: 'tree-dark', at: [1550, 600], mode: 'Dark', signature: 'tree-dark.png', role: 'Primary right-edge anchor at night: the same tree in a cooler, deeper palette', motion: 'None', mobile: 'Keep, crop strategically to the trunk and lower crown' },
      { name: 'branch-light-01', at: [[300, 90], [630, 177]], mode: 'Light', signature: 'branch-light-01.png', role: 'Upper canopy extension along the top edge; its heavy base sits on the right canvas edge to meet the crown', motion: 'Subtle rotation around the right-side base, about ±0.5–0.8deg, 20–30s', mobile: 'Optional' },
      { name: 'branch-dark-01', at: [1100, 90], mode: 'Dark', signature: 'branch-dark-01.png', role: 'Upper canopy extension along the top edge, night palette; base on the right canvas edge', motion: 'Subtle rotation around the right-side base, about ±0.5–0.8deg, 20–30s', mobile: 'Optional' },
      { name: 'branch-light-02', at: [250, 220], mode: 'Light', signature: 'branch-light-02.png', role: 'Lower canopy layer, a second flowering branch; base on the right canvas edge', motion: 'Subtle rotation around the right-side base, about ±0.8–1deg, 16–24s', mobile: 'Optional' },
      { name: 'branch-dark-02', at: [[1100, 220], [935, 255]], mode: 'Dark', signature: 'branch-dark-02.png', role: 'Lower canopy layer, night palette; base on the right canvas edge', motion: 'Subtle rotation around the right-side base, about ±0.8–1deg, 16–24s', mobile: 'Optional' },
      { name: 'blossom-twig-light-01', at: [110, 510], mode: 'Light', role: 'Short blossoming twig to hang from a branch', motion: 'Rotate around the stem end, ±1–2deg, 10–15s', mobile: 'Optional' },
      { name: 'blossom-twig-light-02', at: [280, 510], mode: 'Light', role: 'Short blossoming twig', motion: 'Rotate around the stem end, ±1–2deg, 10–15s', mobile: 'Optional' },
      { name: 'blossom-twig-light-03', at: [450, 515], mode: 'Light', role: 'Short blossoming twig', motion: 'Rotate around the stem end, ±1–2deg, 10–15s', mobile: 'Optional' },
      { name: 'blossom-twig-dark-01', at: [940, 510], mode: 'Dark', role: 'Short blossoming twig, night palette', motion: 'Rotate around the stem end, ±1–2deg, 10–15s', mobile: 'Optional' },
      { name: 'blossom-twig-dark-02', at: [1110, 510], mode: 'Dark', role: 'Short blossoming twig, night palette', motion: 'Rotate around the stem end, ±1–2deg, 10–15s', mobile: 'Optional' },
      { name: 'blossom-twig-dark-03', at: [1280, 515], mode: 'Dark', role: 'Short blossoming twig, night palette', motion: 'Rotate around the stem end, ±1–2deg, 10–15s', mobile: 'Optional' },
      { name: 'leaf-light-01', at: [65, 625], mode: 'Light', role: 'Single leaf for clusters at branch tips', motion: 'Rotate around the stalk, ±2–4deg, 6–10s', mobile: 'Optional' },
      { name: 'leaf-light-02', at: [165, 622], mode: 'Light', role: 'Pair of leaves on a stalk', motion: 'Rotate around the stalk, ±2–4deg, 6–10s', mobile: 'Optional' },
      { name: 'leaf-light-03', at: [285, 622], mode: 'Light', role: 'Leafy sprig', motion: 'Rotate around the stalk, ±2–3deg, 7–11s', mobile: 'Optional' },
      { name: 'leaf-light-04', at: [380, 618], mode: 'Light', role: 'Single narrow leaf', motion: 'Rotate around the stalk, ±2–4deg, 6–10s', mobile: 'Optional' },
      { name: 'leaf-light-05', at: [458, 615], mode: 'Light', role: 'Single broad leaf', motion: 'Rotate around the stalk, ±2–4deg, 6–10s', mobile: 'Optional' },
      { name: 'leaf-dark-01', at: [895, 625], mode: 'Dark', role: 'Single leaf, night palette', motion: 'Rotate around the stalk, ±2–4deg, 6–10s', mobile: 'Optional' },
      { name: 'leaf-dark-02', at: [998, 622], mode: 'Dark', role: 'Pair of leaves, night palette', motion: 'Rotate around the stalk, ±2–4deg, 6–10s', mobile: 'Optional' },
      { name: 'leaf-dark-03', at: [1115, 622], mode: 'Dark', role: 'Leafy sprig, night palette', motion: 'Rotate around the stalk, ±2–3deg, 7–11s', mobile: 'Optional' },
      { name: 'leaf-dark-04', at: [1208, 618], mode: 'Dark', role: 'Single narrow leaf, night palette', motion: 'Rotate around the stalk, ±2–4deg, 6–10s', mobile: 'Optional' },
      { name: 'leaf-dark-05', at: [1290, 615], mode: 'Dark', role: 'Single broad leaf, night palette', motion: 'Rotate around the stalk, ±2–4deg, 6–10s', mobile: 'Optional' },
      { name: 'blossom-light-01', at: [95, 720], mode: 'Light', role: 'Large blossom cluster for the canopy', motion: 'Small rotate, ±1.5–3deg, 8–12s', mobile: 'Optional' },
      { name: 'blossom-light-02', at: [245, 720], mode: 'Light', role: 'Medium blossom cluster', motion: 'Small rotate, ±1.5–3deg, 8–12s', mobile: 'Optional' },
      { name: 'blossom-light-03', at: [358, 718], mode: 'Light', role: 'Medium blossom cluster with leaves', motion: 'Small rotate, ±1.5–3deg, 8–12s', mobile: 'Optional' },
      { name: 'bud-sprig-light', at: [457, 710], mode: 'Light', role: 'Sprig of closed buds', motion: 'Rotate around the stem, ±2–3deg, 7–10s', mobile: 'Optional' },
      { name: 'blossom-dark-01', at: [930, 720], mode: 'Dark', role: 'Large blossom cluster, night palette', motion: 'Small rotate, ±1.5–3deg, 8–12s', mobile: 'Optional' },
      { name: 'blossom-dark-02', at: [1075, 720], mode: 'Dark', role: 'Medium blossom cluster with a glowing mote, night palette', motion: 'Small rotate, ±1.5–3deg, 8–12s', mobile: 'Optional' },
      { name: 'blossom-dark-03', at: [1190, 718], mode: 'Dark', role: 'Medium blossom cluster, night palette', motion: 'Small rotate, ±1.5–3deg, 8–12s', mobile: 'Optional' },
      { name: 'bud-sprig-dark', at: [1287, 710], mode: 'Dark', role: 'Sprig of closed buds, night palette', motion: 'Rotate around the stem, ±2–3deg, 7–10s', mobile: 'Optional' },
      { name: 'falling-leaf-light-01', at: [47, 807], mode: 'Light', role: 'Loose leaf that drifts down', motion: 'Fall: slow translate down with sideways sway and spin; rare, 30–50s cycle', mobile: 'Optional' },
      { name: 'falling-leaf-light-02', at: [165, 800], mode: 'Light', role: 'Loose leaf that drifts down', motion: 'Fall, as above, offset', mobile: 'Optional' },
      { name: 'falling-leaf-light-03', at: [258, 810], mode: 'Light', role: 'Loose leaf that drifts down', motion: 'Fall, as above, offset', mobile: 'Optional' },
      { name: 'falling-petal-light-01', at: [110, 802], mode: 'Light', role: 'Loose petal that drifts down', motion: 'Fall: slower and lighter than leaves, more spin; 25–45s', mobile: 'Optional' },
      { name: 'falling-petal-light-02', at: [218, 800], mode: 'Light', role: 'Loose petal', motion: 'Fall, as above, offset', mobile: 'Optional' },
      { name: 'falling-petal-light-03', at: [311, 795], mode: 'Light', role: 'Loose petal', motion: 'Fall, as above, offset', mobile: 'Optional' },
      { name: 'falling-petal-light-04', at: [368, 800], mode: 'Light', role: 'Loose petal', motion: 'Fall, as above, offset', mobile: 'Optional' },
      { name: 'falling-petal-light-05', at: [434, 798], mode: 'Light', role: 'Large loose petal', motion: 'Fall, as above, offset', mobile: 'Optional' },
      { name: 'falling-leaf-dark-01', at: [880, 807], mode: 'Dark', role: 'Loose leaf, night palette', motion: 'Fall: slow translate down with sway and spin; rare', mobile: 'Optional' },
      { name: 'falling-leaf-dark-02', at: [997, 800], mode: 'Dark', role: 'Loose leaf, night palette', motion: 'Fall, as above, offset', mobile: 'Optional' },
      { name: 'falling-leaf-dark-03', at: [1090, 810], mode: 'Dark', role: 'Loose leaf, night palette', motion: 'Fall, as above, offset', mobile: 'Optional' },
      { name: 'falling-petal-dark-01', at: [940, 802], mode: 'Dark', role: 'Loose petal, night palette', motion: 'Fall: slower than leaves, more spin', mobile: 'Optional' },
      { name: 'falling-petal-dark-02', at: [1050, 800], mode: 'Dark', role: 'Loose petal, night palette', motion: 'Fall, as above, offset', mobile: 'Optional' },
      { name: 'falling-petal-dark-03', at: [1143, 795], mode: 'Dark', role: 'Loose petal, night palette', motion: 'Fall, as above, offset', mobile: 'Optional' },
      { name: 'falling-petal-dark-04', at: [1200, 800], mode: 'Dark', role: 'Loose petal, night palette', motion: 'Fall, as above, offset', mobile: 'Optional' },
      { name: 'falling-petal-dark-05', at: [1265, 798], mode: 'Dark', role: 'Large loose petal, night palette', motion: 'Fall, as above, offset', mobile: 'Optional' },
      { name: 'mushroom-light-01', at: [65, 885], mode: 'Light', role: 'Single toadstool with a small one, for the ground line', motion: 'None, or a near-invisible cap breathe (scale ≤1.02, 10–14s)', mobile: 'Optional' },
      { name: 'mushroom-light-02', at: [180, 885], mode: 'Light', role: 'Group of three toadstools', motion: 'None, or a near-invisible cap breathe', mobile: 'Optional' },
      { name: 'mushroom-light-03', at: [310, 885], mode: 'Light', role: 'Pair of toadstools in moss', motion: 'None, or a near-invisible cap breathe', mobile: 'Optional' },
      { name: 'stump-light', at: [440, 880], mode: 'Light', role: 'Mossy stump with a toadstool and a flower', motion: 'None', mobile: 'Optional' },
      { name: 'mushroom-dark-01', at: [900, 885], mode: 'Dark', role: 'Toadstool, night palette', motion: 'None, or a near-invisible cap breathe', mobile: 'Optional' },
      { name: 'mushroom-dark-02', at: [1020, 885], mode: 'Dark', role: 'Group of glowing toadstools', motion: 'Slow glow breathe (opacity 0.85–1, 6–10s)', mobile: 'Optional' },
      { name: 'mushroom-dark-03', at: [1158, 885], mode: 'Dark', role: 'Pair of glowing toadstools', motion: 'Slow glow breathe (opacity 0.85–1, 6–10s)', mobile: 'Optional' },
      { name: 'stump-dark', at: [1300, 885], mode: 'Dark', role: 'Mossy stump with a toadstool and glowing motes', motion: 'None', mobile: 'Optional' },
      { name: 'cottage', at: [700, 890], mode: 'Light', role: 'Small fairy cottage nestled in moss, for the foot of the tree', motion: 'None', mobile: 'Optional' },
      { name: 'firefly-01', at: [1410, 870], mode: 'Dark', role: 'Small firefly glow', motion: 'Slow translate drift + opacity pulse, 10–20s', mobile: 'Optional' },
      { name: 'firefly-02', at: [1445, 905], mode: 'Dark', role: 'Firefly glow with star rays', motion: 'Slow translate drift + opacity pulse, offset', mobile: 'Optional' },
      { name: 'firefly-03', at: [1510, 865], mode: 'Dark', role: 'Small firefly glow', motion: 'Slow translate drift + opacity pulse, offset', mobile: 'Optional' },
      { name: 'firefly-04', at: [1534, 907], mode: 'Dark', role: 'Firefly glow with star rays', motion: 'Slow translate drift + opacity pulse, offset', mobile: 'Optional' },
      { name: 'firefly-bug', at: [1608, 880], mode: 'Dark', role: 'Firefly insect with wings and a glowing tail, the one close-up firefly', motion: 'Slow wandering translate; tail opacity pulse', mobile: 'Optional' }
    ]
  },
  cottagecore: {
    title: 'Cottagecore',
    sheet: 'cottagecore-assets.png',
    dir: 'cottagecore',
    groupDistance: 6,
    cuts: [
      // The robin's head almost touches the meadow above it.
      [20, 577, 330, 577],
      // The tail of the second smoke plume meets the top of the signpost.
      [1184, 738, 1190, 763], [1190, 763, 1270, 763],
      // Fireflies whose glows overlap each other or the second signpost.
      [1390, 738, 1475, 738],
      [1516, 720, 1556, 668],
      [1560, 668, 1630, 708]
    ],
    assets: [
      { name: 'cottage-light', at: [300, 250], mode: 'Light', signature: 'cottage-light.png', role: 'Signature object: rose-covered stone cottage with its garden path. Front-facing single gable, chimney on the left', motion: 'None', mobile: 'Keep; scale down and anchor to a bottom corner' },
      { name: 'cottage-dark', at: [890, 250], mode: 'Dark', signature: 'cottage-dark.png', role: 'Signature object at dusk: the same front-facing cottage as cottage-light, windows and lantern lit. No smoke painted in, so pair with the separate smoke plumes', motion: 'None; pair with a separate drifting smoke plume', mobile: 'Keep; scale down and anchor to a bottom corner' },
      { name: 'toadstools-red', at: [1300, 140], mode: 'Both', role: 'Pair of red spotted toadstools in daisies', motion: 'None, or a near-invisible cap breathe (scale ≤1.02, 10–14s)', mobile: 'Optional' },
      { name: 'mushrooms-brown', at: [1535, 130], mode: 'Both', role: 'Group of brown mushrooms with a stone', motion: 'None, or a near-invisible cap breathe', mobile: 'Optional' },
      { name: 'mushrooms-tall', at: [1290, 330], mode: 'Both', role: 'Cluster of tall slender mushrooms in daisies', motion: 'None, or a near-invisible cap breathe', mobile: 'Optional' },
      { name: 'toadstools-cluster', at: [1535, 330], mode: 'Both', role: 'Cluster of red spotted toadstools with flowers', motion: 'None, or a near-invisible cap breathe', mobile: 'Optional' },
      { name: 'wildflowers-01', at: [160, 500], mode: 'Both', role: 'Wildflower meadow tuft: daisies and pink and yellow flowers', motion: 'Sway around the base, ±1–2deg, 8–12s', mobile: 'Keep one tuft' },
      { name: 'wildflowers-02', at: [425, 500], mode: 'Both', role: 'Meadow tuft with cow parsley and daisies', motion: 'Sway around the base, ±1–2deg, 8–12s', mobile: 'Optional' },
      { name: 'wildflowers-lavender', at: [650, 500], mode: 'Both', role: 'Lavender and daisies with a stone', motion: 'Sway around the base, ±1–2deg, 9–13s', mobile: 'Optional' },
      { name: 'mossy-stones', at: [880, 520], mode: 'Both', role: 'Mossy stones with small flowers, a low ground piece', motion: 'None', mobile: 'Optional' },
      { name: 'vine-01', at: [1110, 500], mode: 'Both', role: 'Ivy vine with white flowers, to hang from the top edge', motion: 'Sway around the top end, ±1.5–2deg, 10–14s', mobile: 'Optional' },
      { name: 'vine-roses', at: [1310, 500], mode: 'Both', role: 'Ivy vine with pink roses', motion: 'Sway around the top end, ±1.5–2deg, 10–14s', mobile: 'Optional' },
      { name: 'vine-02', at: [1470, 520], mode: 'Both', role: 'Ivy vine with white flowers', motion: 'Sway around the top end, ±1.5–2deg, 10–14s', mobile: 'Optional' },
      { name: 'vine-03', at: [1600, 520], mode: 'Both', role: 'Short ivy vine with small flowers', motion: 'Sway around the top end, ±2deg, 9–12s', mobile: 'Optional' },
      { name: 'fence-robin', at: [150, 680], mode: 'Both', role: 'Wooden fence corner with a robin and wildflowers', motion: 'None (the robin is painted in)', mobile: 'Optional' },
      { name: 'fence', at: [515, 680], mode: 'Both', role: 'Wooden fence overgrown with roses and daisies', motion: 'None', mobile: 'Optional' },
      { name: 'lantern', at: [770, 660], mode: 'Both', role: 'Hanging iron lantern with a lit candle', motion: 'Gentle swing around the ring, ±1.5deg, 6–8s; flame opacity flicker', mobile: 'Optional' },
      { name: 'lantern-ivy', at: [920, 680], mode: 'Both', role: 'Lit lantern wrapped in ivy', motion: 'Gentle swing, ±1deg; flame opacity flicker', mobile: 'Optional' },
      { name: 'smoke-01', at: [1110, 660], mode: 'Both', role: 'Pale chimney smoke plume', motion: 'Rise and fade: translate up, scale up, opacity out; 8–12s, staggered copies', mobile: 'Optional' },
      { name: 'smoke-02', at: [1260, 660], mode: 'Both', role: 'Greyer chimney smoke plume', motion: 'Rise and fade, as above', mobile: 'Optional' },
      { name: 'firefly-bug-01', at: [1378, 650], mode: 'Dark', role: 'Firefly insect with a glowing tail', motion: 'Slow wandering translate; tail opacity pulse, 4–7s', mobile: 'Optional' },
      { name: 'firefly-bug-02', at: [1515, 675], mode: 'Dark', role: 'Firefly insect with a glowing tail', motion: 'Slow wandering translate; tail opacity pulse, offset', mobile: 'Optional' },
      { name: 'firefly-bug-03', at: [1420, 705], mode: 'Dark', role: 'Firefly insect with a glowing tail', motion: 'Slow wandering translate; tail opacity pulse, offset', mobile: 'Optional' },
      { name: 'firefly-01', at: [1455, 640], mode: 'Dark', role: 'Firefly glow', motion: 'Slow translate drift + opacity pulse, 10–20s', mobile: 'Optional' },
      { name: 'firefly-02', at: [1600, 652], mode: 'Dark', role: 'Firefly glow', motion: 'Slow translate drift + opacity pulse, offset', mobile: 'Optional' },
      { name: 'firefly-03', at: [1562, 714], mode: 'Dark', role: 'Large firefly glow', motion: 'Slow translate drift + opacity pulse, offset', mobile: 'Optional' },
      { name: 'firefly-04', at: [1345, 718], mode: 'Dark', role: 'Small firefly glow', motion: 'Slow translate drift + opacity pulse, offset', mobile: 'Optional' },
      { name: 'garden-basket', at: [245, 850], mode: 'Both', role: 'Wicker basket and watering can among flowers and stones', motion: 'None', mobile: 'Optional' },
      { name: 'stone-wall', at: [710, 860], mode: 'Both', role: 'Low dry-stone wall overgrown with roses and daisies, a ground strip', motion: 'None', mobile: 'Optional' },
      { name: 'signpost-01', at: [1200, 840], mode: 'Both', role: 'Wooden two-way signpost with roses', motion: 'None', mobile: 'Optional' },
      { name: 'signpost-02', at: [1500, 840], mode: 'Both', role: 'Wooden signpost with ivy and daisies', motion: 'None', mobile: 'Optional' }
    ]
  },
  space: {
    title: 'Space',
    sheet: 'space-assets.png',
    dir: 'space',
    // Space glows are broad, so objects are found on their bright cores and the glow is handed
    // back through a longer reach.
    detectAlpha: 200,
    territory: 160,
    groupDistance: 8,
    cuts: [
      // Each ringed planet is painted over the top of its galaxy and they share a soft glow; this
      // line follows the lower edge of the planet (see the asset report).
      [20, 256, 250, 256], [250, 256, 330, 270], [330, 270, 500, 276], [500, 276, 720, 262],
      [860, 275, 1000, 268], [1000, 268, 1320, 272], [1320, 272, 1560, 265]
    ],
    assets: [
      { name: 'planet-ringed-light', at: [330, 120], mode: 'Light', signature: 'planet-ringed-light.png', role: 'Signature object for the top-right corner: ringed planet, ring rising to the left. Faint glow reaches the left and right canvas edges', motion: 'Very slow drift (a few px over 90–120s)', mobile: 'Keep, scaled down and cropped by the corner' },
      { name: 'planet-ringed-dark', at: [1150, 120], mode: 'Dark', signature: 'planet-ringed-dark.png', role: 'Signature object for the top-right corner, night palette: same ring tilt and light direction as planet-ringed-light, glow fully inside the canvas', motion: 'Very slow drift (a few px over 90–120s)', mobile: 'Keep, scaled down and cropped by the corner' },
      { name: 'galaxy-light', at: [[350, 355], [125, 297], [620, 415], [705, 412]], mode: 'Light', signature: 'galaxy-light.png', role: 'Deep-background spiral galaxy for the opposite corner', motion: 'Extremely slow rotation (360deg over 10+ min), or none', mobile: 'Optional / reduced opacity' },
      { name: 'galaxy-dark', at: [[1250, 355], [940, 342], [985, 392], [1598, 403]], mode: 'Dark', signature: 'galaxy-dark.png', role: 'Deep-background spiral galaxy, night palette. The gaps between the arms are painted opaque navy, so it carries its own dark disc', motion: 'Extremely slow rotation (360deg over 10+ min), or none', mobile: 'Optional / reduced opacity' },
      { name: 'nebula-light-01', at: [200, 530], mode: 'Light', role: 'Glowing nebula cloud for an edge band', motion: 'Very slow horizontal drift and opacity breathe, 60–90s', mobile: 'Optional' },
      { name: 'nebula-light-02', at: [640, 550], mode: 'Light', role: 'Glowing nebula cloud', motion: 'Very slow horizontal drift and opacity breathe, 60–90s', mobile: 'Optional' },
      { name: 'nebula-dark-01', at: [1050, 540], mode: 'Dark', role: 'Nebula cloud, night palette', motion: 'Very slow drift and opacity breathe, 60–90s', mobile: 'Optional' },
      { name: 'nebula-dark-02', at: [1470, 560], mode: 'Dark', role: 'Nebula cloud, night palette', motion: 'Very slow drift and opacity breathe, 60–90s', mobile: 'Optional' },
      { name: 'asteroid-belt-light', at: [[400, 680], [75, 628], [97, 630], [60, 638], [78, 652], [118, 671]], mode: 'Light', role: 'Trail of asteroids thinning to dust, for the lower edge', motion: 'Slow translate along the trail, 90–120s', mobile: 'Optional' },
      { name: 'asteroid-belt-dark', at: [[960, 665], [1038, 697], [1098, 672], [1113, 705], [1175, 680], [1200, 716], [1360, 700], [1280, 665], [908, 627], [877, 638], [903, 658]], mode: 'Dark', role: 'Trail of asteroids thinning to dust, night palette', motion: 'Slow translate along the trail, 90–120s', mobile: 'Optional' },
      { name: 'planet-light-01', at: [105, 780], mode: 'Light', role: 'Large banded planet', motion: 'Very slow drift, a few px over 60–120s', mobile: 'Optional' },
      { name: 'planet-light-02', at: [232, 795], mode: 'Light', role: 'Medium banded planet', motion: 'Very slow drift, a few px over 60–120s', mobile: 'Optional' },
      { name: 'planet-light-03', at: [325, 805], mode: 'Light', role: 'Small planet', motion: 'Very slow drift', mobile: 'Optional' },
      { name: 'moon-light', at: [415, 795], mode: 'Light', role: 'Cratered moon', motion: 'Very slow drift, or a slow orbit around a larger planet', mobile: 'Optional' },
      { name: 'planet-light-04', at: [507, 805], mode: 'Light', role: 'Small violet planet', motion: 'Very slow drift', mobile: 'Optional' },
      { name: 'planet-light-05', at: [582, 805], mode: 'Light', role: 'Small grey planet', motion: 'Very slow drift', mobile: 'Optional' },
      { name: 'planet-light-06', at: [668, 788], mode: 'Light', role: 'Medium pale planet', motion: 'Very slow drift', mobile: 'Optional' },
      { name: 'planet-light-07', at: [750, 775], mode: 'Light', role: 'Tiny distant planet', motion: 'None', mobile: 'Optional' },
      { name: 'planet-dark-01', at: [938, 785], mode: 'Dark', role: 'Large banded planet, night palette', motion: 'Very slow drift, a few px over 60–120s', mobile: 'Optional' },
      { name: 'planet-dark-02', at: [1065, 797], mode: 'Dark', role: 'Medium planet, night palette', motion: 'Very slow drift', mobile: 'Optional' },
      { name: 'moon-dark', at: [1175, 797], mode: 'Dark', role: 'Cratered moon, night palette', motion: 'Very slow drift, or a slow orbit around a larger planet', mobile: 'Optional' },
      { name: 'planet-dark-03', at: [1272, 805], mode: 'Dark', role: 'Small planet, night palette', motion: 'Very slow drift', mobile: 'Optional' },
      { name: 'planet-dark-04', at: [1355, 795], mode: 'Dark', role: 'Small cratered planet, night palette', motion: 'Very slow drift', mobile: 'Optional' },
      { name: 'planet-dark-05', at: [1428, 808], mode: 'Dark', role: 'Tiny distant planet, night palette', motion: 'None', mobile: 'Optional' },
      { name: 'planet-dark-06', at: [1507, 788], mode: 'Dark', role: 'Medium blue planet, night palette', motion: 'Very slow drift', mobile: 'Optional' },
      { name: 'planet-dark-07', at: [1592, 778], mode: 'Dark', role: 'Tiny distant planet, night palette', motion: 'None', mobile: 'Optional' },
      { name: 'sparkles-light-01', at: [[63, 880], [108, 900], [80, 920]], mode: 'Light', role: 'Group of three four-point stars', motion: 'Twinkle: opacity 0.3–1, scale 0.9–1.05, 3–8s, own clock', mobile: 'Optional' },
      { name: 'sparkles-light-02', at: [216, 893], mode: 'Light', role: 'Cluster of tiny sparkles (stardust)', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'star-light-01', at: [333, 893], mode: 'Light', role: 'Single bright four-point star', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'sparkles-light-03', at: [[428, 887], [443, 900]], mode: 'Light', role: 'Pair of small warm sparkles', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'star-light-02', at: [562, 885], mode: 'Light', role: 'Single violet four-point star', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'sparkles-light-04', at: [668, 887], mode: 'Light', role: 'Star with surrounding stardust', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'star-light-03', at: [770, 882], mode: 'Light', role: 'Small warm star', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'sparkles-dark-01', at: [[877, 890], [907, 870], [920, 905]], mode: 'Dark', role: 'Group of three four-point stars, night palette', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'sparkles-dark-02', at: [[1005, 882], [1025, 898], [1052, 883]], mode: 'Dark', role: 'Cluster of small sparkles, night palette', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'star-dark-01', at: [1145, 897], mode: 'Dark', role: 'Single blue four-point star', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'sparkles-dark-03', at: [1253, 895], mode: 'Dark', role: 'Cluster of tiny sparkles, night palette', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'shooting-star-01', at: [1385, 872], mode: 'Dark', role: 'Short shooting star with a warm head', motion: 'Very rare (once per 40–90s): quick diagonal translate, opacity in and out', mobile: 'Optional' },
      { name: 'shooting-star-02', at: [1445, 890], mode: 'Dark', role: 'Long shooting star', motion: 'Very rare: quick diagonal translate, opacity in and out', mobile: 'Optional' },
      { name: 'shooting-star-03', at: [1585, 885], mode: 'Dark', role: 'Blue shooting star', motion: 'Very rare: quick diagonal translate, opacity in and out', mobile: 'Optional' }
    ]
  },
  cyberpunk: {
    title: 'Cyberpunk',
    sheet: 'cyberpunk-assets.png',
    dir: 'cyberpunk',
    // The objects sit only a few pixels apart and their neon glows overlap, so grouping is tight;
    // antenna tips and lamp posts that detach join their skyline or overpass as strays.
    detectAlpha: 40,
    groupDistance: 2,
    assets: [
      { name: 'sun-light', at: [195, 130], mode: 'Light', signature: 'sun-light.png', role: 'Signature object: striped synthwave sun behind the horizon. The stripe gaps are cut out (transparent)', motion: 'Slow glow breathe (opacity 0.85–1, 6–9s); a rare sub-second glitch offset', mobile: 'Keep; the signature object' },
      { name: 'sun-dark', at: [1040, 135], mode: 'Dark', signature: 'sun-dark.png', role: 'Signature object, night palette. Same striped geometry as sun-light, with the stripe gaps cut out (transparent)', motion: 'Slow glow breathe; a rare sub-second glitch offset', mobile: 'Keep; the signature object' },
      { name: 'skyline-light', at: [600, 130], mode: 'Light', signature: 'skyline-light.png', role: 'Horizon city anchor: pastel neon skyline with palms', motion: 'None; windows may flicker through a separate overlay', mobile: 'Simplify/crop to the centre' },
      { name: 'skyline-dark', at: [1420, 130], mode: 'Dark', signature: 'skyline-dark.png', role: 'Horizon city anchor at night: lit towers, a bridge and palms', motion: 'None', mobile: 'Simplify/crop to the centre' },
      { name: 'grid-floor-light', at: [420, 300], mode: 'Light', role: 'Perspective neon grid floor reaching to the horizon', motion: 'None as an image; a CSS grid on top can carry the roll-towards-viewer motion', mobile: 'Keep' },
      { name: 'grid-floor-dark', at: [1250, 305], mode: 'Dark', role: 'Perspective neon grid floor, night palette', motion: 'As above', mobile: 'Keep' },
      { name: 'car-light-01', at: [115, 408], mode: 'Light', role: 'Hover car, side view', motion: 'Rare slow pass across the skyline band (translate X over 20–40s, then a long pause)', mobile: 'Optional' },
      { name: 'car-light-02', at: [315, 405], mode: 'Light', role: 'Hover car with a glowing wheel ring', motion: 'Rare slow pass, offset', mobile: 'Optional' },
      { name: 'hovercraft-light-01', at: [515, 413], mode: 'Light', role: 'Winged hover craft with thrusters', motion: 'Rare slow pass, offset', mobile: 'Optional' },
      { name: 'hovercraft-light-02', at: [727, 403], mode: 'Light', role: 'Boxy hover van with thrusters', motion: 'Rare slow pass, offset', mobile: 'Optional' },
      { name: 'car-dark-01', at: [955, 410], mode: 'Dark', role: 'Hover car, night palette', motion: 'Rare slow pass', mobile: 'Optional' },
      { name: 'car-dark-02', at: [1160, 405], mode: 'Dark', role: 'Hover car with a glowing wheel ring, night palette', motion: 'Rare slow pass, offset', mobile: 'Optional' },
      { name: 'hovercraft-dark-01', at: [1355, 405], mode: 'Dark', role: 'Winged hover craft, night palette', motion: 'Rare slow pass, offset', mobile: 'Optional' },
      { name: 'hovercraft-dark-02', at: [1560, 405], mode: 'Dark', role: 'Boxy hover van, night palette', motion: 'Rare slow pass, offset', mobile: 'Optional' },
      { name: 'billboard-palm-light', at: [125, 555], mode: 'Light', role: 'Neon billboard: sunset and palm', motion: 'Sign flicker: brief opacity dips, rare, 12–25s cycle', mobile: 'Optional' },
      { name: 'billboard-blossom-light', at: [308, 555], mode: 'Light', role: 'Neon billboard: cherry blossom', motion: 'Sign flicker, own clock', mobile: 'Optional' },
      { name: 'billboard-mountains-light', at: [500, 555], mode: 'Light', role: 'Neon billboard: sun over mountains', motion: 'Sign flicker, own clock', mobile: 'Optional' },
      { name: 'billboard-statue-light', at: [700, 555], mode: 'Light', role: 'Neon billboard: classical statue head', motion: 'Sign flicker, own clock', mobile: 'Optional' },
      { name: 'billboard-palm-dark', at: [965, 555], mode: 'Dark', role: 'Neon billboard: palm tree', motion: 'Sign flicker, own clock', mobile: 'Optional' },
      { name: 'billboard-waves-dark', at: [1145, 555], mode: 'Dark', role: 'Neon billboard: flowing waves', motion: 'Sign flicker, own clock', mobile: 'Optional' },
      { name: 'billboard-statue-dark', at: [1340, 555], mode: 'Dark', role: 'Neon billboard: statue head', motion: 'Sign flicker, own clock', mobile: 'Optional' },
      { name: 'billboard-sun-dark', at: [1535, 555], mode: 'Dark', role: 'Neon billboard: striped sun', motion: 'Sign flicker, own clock', mobile: 'Optional' },
      { name: 'wall-light-01', at: [105, 700], mode: 'Light', role: 'Concrete wall with a pink neon strip, for a lower corner', motion: 'None; neon may breathe slightly', mobile: 'Optional' },
      { name: 'wall-light-02', at: [300, 712], mode: 'Light', role: 'Low concrete wall with neon trim', motion: 'None', mobile: 'Optional' },
      { name: 'wall-light-03', at: [510, 712], mode: 'Light', role: 'Angled concrete structure with blue and pink neon and palms', motion: 'None', mobile: 'Optional' },
      { name: 'wall-light-04', at: [727, 715], mode: 'Light', role: 'Angled concrete structure with blue neon', motion: 'None', mobile: 'Optional' },
      { name: 'wall-dark-01', at: [945, 710], mode: 'Dark', role: 'Concrete wall with a pink neon strip, night palette', motion: 'None', mobile: 'Optional' },
      { name: 'wall-dark-02', at: [1140, 712], mode: 'Dark', role: 'Low concrete wall with neon trim, night palette', motion: 'None', mobile: 'Optional' },
      { name: 'wall-dark-03', at: [1350, 712], mode: 'Dark', role: 'Angled concrete structure with neon, night palette', motion: 'None', mobile: 'Optional' },
      { name: 'wall-dark-04', at: [1560, 712], mode: 'Dark', role: 'Angled concrete structure with blue neon, night palette', motion: 'None', mobile: 'Optional' },
      { name: 'overpass-light-01', at: [200, 820], mode: 'Light', role: 'Elevated highway with palms and pink neon', motion: 'None', mobile: 'Optional' },
      { name: 'overpass-light-02', at: [620, 820], mode: 'Light', role: 'Curved elevated highway with a palm', motion: 'None', mobile: 'Optional' },
      { name: 'overpass-dark-01', at: [1035, 825], mode: 'Dark', role: 'Elevated highway with street lights, night palette', motion: 'None', mobile: 'Optional' },
      { name: 'overpass-dark-02', at: [1455, 825], mode: 'Dark', role: 'Curved elevated highway, night palette', motion: 'None', mobile: 'Optional' },
      { name: 'lens-flare-light', at: [135, 900], mode: 'Light', role: 'Horizontal lens flare, for the horizon line', motion: 'Slow opacity breathe, 6–10s', mobile: 'Optional' },
      { name: 'scanlines-light', at: [330, 900], mode: 'Light', role: 'Short block of neon scan lines (sign or HUD detail)', motion: 'Occasional flicker', mobile: 'Optional' },
      { name: 'light-streak-light', at: [508, 904], mode: 'Light', role: 'Thin blue light streak', motion: 'Slow opacity breathe, or a sweep translate', mobile: 'Optional' },
      { name: 'halftone-light', at: [710, 900], mode: 'Light', role: 'Halftone dot glow strip', motion: 'None, or a slow opacity breathe', mobile: 'Optional' },
      { name: 'lens-flare-dark', at: [975, 903], mode: 'Dark', role: 'Horizontal magenta lens flare, for the horizon line', motion: 'Slow opacity breathe, 6–10s', mobile: 'Optional' },
      { name: 'scanlines-dark', at: [1165, 900], mode: 'Dark', role: 'Block of violet scan lines', motion: 'Occasional flicker', mobile: 'Optional' },
      { name: 'neon-ring-dark', at: [1335, 905], mode: 'Dark', role: 'Flat neon ring (a floor light or portal)', motion: 'Slow opacity breathe', mobile: 'Optional' },
      { name: 'halftone-dark', at: [1530, 900], mode: 'Dark', role: 'Halftone dot glow strip, night palette', motion: 'None, or a slow opacity breathe', mobile: 'Optional' }
    ]
  },
  pastel: {
    title: 'Pastel',
    sheet: 'pastel-assets.png',
    dir: 'pastel',
    // The bubble clouds stand a few pixels apart, so grouping is tight.
    groupDistance: 3,
    cuts: [
      // Two dark bubble clouds whose wisps touch.
      [1119, 440, 1119, 548]
    ],
    assets: [
      { name: 'cloud-light-01', at: [215, 120], mode: 'Light', role: 'Large rainbow-tinted cloud', motion: 'Slow horizontal drift, 2–5vw over 90–160s; layers at different speeds', mobile: 'Keep one large cloud' },
      { name: 'cloud-light-02', at: [625, 120], mode: 'Light', role: 'Large mint and pink cloud', motion: 'Slow horizontal drift, own speed', mobile: 'Optional' },
      { name: 'cloud-light-03', at: [215, 310], mode: 'Light', role: 'Large pastel cloud', motion: 'Slow horizontal drift, own speed', mobile: 'Optional' },
      { name: 'cloud-light-04', at: [625, 310], mode: 'Light', role: 'Large pastel cloud with a butter-yellow front', motion: 'Slow horizontal drift, own speed', mobile: 'Optional' },
      { name: 'cloud-dark-01', at: [1045, 120], mode: 'Dark', role: 'Large dusk cloud with a sparkle', motion: 'Slow horizontal drift, own speed', mobile: 'Keep one large cloud' },
      { name: 'cloud-dark-02', at: [1450, 120], mode: 'Dark', role: 'Large dusk cloud', motion: 'Slow horizontal drift, own speed', mobile: 'Optional' },
      { name: 'cloud-dark-03', at: [1055, 300], mode: 'Dark', role: 'Large dusk cloud with sparkles', motion: 'Slow horizontal drift, own speed', mobile: 'Optional' },
      { name: 'cloud-dark-04', at: [1465, 310], mode: 'Dark', role: 'Large dusk cloud with sparkles', motion: 'Slow horizontal drift, own speed', mobile: 'Optional' },
      { name: 'bubble-cloud-light-01', at: [150, 485], mode: 'Light', role: 'Low cloud of glossy pastel bubbles, for a bottom edge', motion: 'Very slow drift; optional slight float (translateY ±4px, 10–14s)', mobile: 'Optional' },
      { name: 'bubble-cloud-light-02', at: [420, 485], mode: 'Light', role: 'Low cloud of glossy bubbles', motion: 'As above, own clock', mobile: 'Optional' },
      { name: 'bubble-cloud-light-03', at: [690, 485], mode: 'Light', role: 'Low cloud of glossy bubbles', motion: 'As above, own clock', mobile: 'Optional' },
      { name: 'bubble-cloud-dark-01', at: [985, 485], mode: 'Dark', role: 'Low cloud of glossy bubbles, dusk palette', motion: 'As above, own clock', mobile: 'Optional' },
      { name: 'bubble-cloud-dark-02', at: [1255, 485], mode: 'Dark', role: 'Low cloud of glossy bubbles, dusk palette', motion: 'As above, own clock', mobile: 'Optional' },
      { name: 'bubble-cloud-dark-03', at: [1525, 485], mode: 'Dark', role: 'Low cloud of glossy bubbles, dusk palette', motion: 'As above, own clock', mobile: 'Optional' },
      { name: 'rainbow-light-01', at: [225, 640], mode: 'Light', role: 'Soft rainbow arch on clouds', motion: 'None, or a slow opacity breathe', mobile: 'Optional' },
      { name: 'rainbow-light-02', at: [580, 640], mode: 'Light', role: 'Chunky pastel arch on clouds', motion: 'None, or a slow opacity breathe', mobile: 'Optional' },
      { name: 'rainbow-dark-01', at: [1080, 640], mode: 'Dark', role: 'Rainbow arch on dusk clouds with sparkles', motion: 'None, or a slow opacity breathe', mobile: 'Optional' },
      { name: 'rainbow-dark-02', at: [1437, 640], mode: 'Dark', role: 'Lavender arch on dusk clouds', motion: 'None, or a slow opacity breathe', mobile: 'Optional' },
      { name: 'bubble-01', at: [120, 775], mode: 'Both', role: 'Large iridescent soap bubble', motion: 'Slow rise with sideways sway, 30–60s; fade out near the top', mobile: 'Optional' },
      { name: 'bubble-02', at: [278, 770], mode: 'Both', role: 'Medium soap bubble', motion: 'Slow rise with sway, own clock', mobile: 'Optional' },
      { name: 'bubble-03', at: [438, 765], mode: 'Both', role: 'Medium soap bubble', motion: 'Slow rise with sway, own clock', mobile: 'Optional' },
      { name: 'bubble-04', at: [582, 765], mode: 'Both', role: 'Small soap bubble', motion: 'Slow rise with sway, own clock', mobile: 'Optional' },
      { name: 'bubble-05', at: [706, 765], mode: 'Both', role: 'Tiny soap bubble', motion: 'Slow rise with sway, own clock', mobile: 'Optional' },
      { name: 'star-butter', at: [832, 785], mode: 'Both', role: 'Puffy butter-yellow star', motion: 'Slow float and a few degrees of turn, 40–70s', mobile: 'Optional' },
      { name: 'star-pink', at: [902, 737], mode: 'Both', role: 'Puffy pink star', motion: 'Slow float and turn, own clock', mobile: 'Optional' },
      { name: 'star-sky', at: [945, 790], mode: 'Both', role: 'Puffy sky-blue star', motion: 'Slow float and turn, own clock', mobile: 'Optional' },
      { name: 'sparkle-01', at: [1032, 763], mode: 'Both', role: 'Four-point sparkle, butter yellow', motion: 'Twinkle: opacity and scale, 3–7s, own clock', mobile: 'Optional' },
      { name: 'sparkle-02', at: [1102, 748], mode: 'Both', role: 'Four-point sparkle, pink', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'sparkle-03', at: [1170, 763], mode: 'Both', role: 'Tall four-point sparkle, sky blue', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'sparkle-04', at: [1270, 755], mode: 'Both', role: 'Four-point sparkle, butter yellow', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'sparkle-05', at: [1365, 742], mode: 'Both', role: 'Small four-point sparkle', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'sparkle-06', at: [1328, 793], mode: 'Both', role: 'Small four-point sparkle, pink', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'sparkle-07', at: [1417, 782], mode: 'Both', role: 'Four-point sparkle, lavender', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'sparkle-08', at: [1477, 744], mode: 'Both', role: 'Four-point sparkle, lavender', motion: 'Twinkle, own clock', mobile: 'Optional' },
      { name: 'moon', at: [1565, 835], mode: 'Both', role: 'Glowing crescent moon', motion: 'Very slow float, a few px over 60s; glow breathe', mobile: 'Optional' },
      { name: 'shooting-star-light', at: [[475, 875], [337, 885], [371, 884], [700, 880], [750, 901]], mode: 'Light', role: 'Shooting star with a pastel trail and small stars', motion: 'Rare: draw across (translate + opacity), once per 40–90s', mobile: 'Optional' },
      { name: 'shooting-star-dark', at: [[1120, 875], [1302, 873]], mode: 'Dark', role: 'Shooting star with a glowing trail, dusk palette', motion: 'Rare: draw across, once per 40–90s', mobile: 'Optional' }
    ]
  },
  'liquid-glass': {
    title: 'Liquid Glass',
    sheet: 'liquid-glass-assets.png',
    dir: 'liquid-glass',
    groupDistance: 4,
    cuts: [
      // A faint bridge joins each large bubble to the swoosh below it.
      [140, 485, 300, 485, 5],
      [960, 484, 1090, 484, 5]
    ],
    assets: [
      { name: 'bubble-cluster-light-01', at: [135, 140], mode: 'Light', role: 'Cluster of overlapping glass bubbles, for a corner', motion: 'Slow drift (2–4vw over 50–80s); clusters at different speeds for depth', mobile: 'Keep one cluster' },
      { name: 'bubble-cluster-light-02', at: [355, 160], mode: 'Light', role: 'Cluster of glass bubbles', motion: 'Slow drift, own speed', mobile: 'Optional' },
      { name: 'bubble-cluster-light-03', at: [[555, 150], [586, 45], [560, 273], [483, 85], [487, 240], [617, 236]], mode: 'Light', role: 'Large bubble with satellites', motion: 'Slow drift, own speed', mobile: 'Optional' },
      { name: 'bubble-cluster-light-04', at: [745, 160], mode: 'Light', role: 'Tight cluster of glass bubbles', motion: 'Slow drift, own speed', mobile: 'Optional' },
      { name: 'bubble-cluster-dark-01', at: [980, 140], mode: 'Dark', role: 'Cluster of dark glass bubbles with amber rims', motion: 'Slow drift, own speed', mobile: 'Keep one cluster' },
      { name: 'bubble-cluster-dark-02', at: [1195, 165], mode: 'Dark', role: 'Cluster of dark glass bubbles', motion: 'Slow drift, own speed', mobile: 'Optional' },
      { name: 'bubble-cluster-dark-03', at: [[1385, 155], [1416, 49], [1389, 273], [1320, 89], [1322, 240], [1446, 236]], mode: 'Dark', role: 'Large dark bubble with satellites', motion: 'Slow drift, own speed', mobile: 'Optional' },
      { name: 'bubble-cluster-dark-04', at: [1570, 160], mode: 'Dark', role: 'Tight cluster of dark glass bubbles', motion: 'Slow drift, own speed', mobile: 'Optional' },
      { name: 'bubble-large-light', at: [200, 370], mode: 'Light', signature: 'bubble-large-light.png', role: 'Large single glass bubble, the near layer. Clear centre (the page shows through), iridescent rim', motion: 'Slow drift (2vw / 70s) with a slight scale breathe', mobile: 'Optional' },
      { name: 'bubble-light-01', at: [403, 395], mode: 'Light', role: 'Tiny glass bubble, the far layer', motion: 'Slow drift, faster than the near layer', mobile: 'Optional' },
      { name: 'bubble-light-02', at: [503, 383], mode: 'Light', role: 'Small glass bubble', motion: 'Slow drift, own speed', mobile: 'Optional' },
      { name: 'bubble-light-03', at: [617, 395], mode: 'Light', role: 'Small glass bubble', motion: 'Slow drift, own speed', mobile: 'Optional' },
      { name: 'bubble-light-04', at: [745, 390], mode: 'Light', role: 'Medium glass bubble', motion: 'Slow drift, own speed', mobile: 'Optional' },
      { name: 'bubble-large-dark', at: [1010, 370], mode: 'Dark', signature: 'bubble-large-dark.png', role: 'Large single glass bubble, the near layer, night palette: deeper blue tinted rim fading to a clear centre (the page shows through)', motion: 'Slow drift with a slight scale breathe', mobile: 'Optional' },
      { name: 'bubble-dark-01', at: [1220, 393], mode: 'Dark', role: 'Tiny dark glass bubble', motion: 'Slow drift, own speed', mobile: 'Optional' },
      { name: 'bubble-dark-02', at: [1320, 380], mode: 'Dark', role: 'Small dark glass bubble', motion: 'Slow drift, own speed', mobile: 'Optional' },
      { name: 'bubble-dark-03', at: [1433, 390], mode: 'Dark', role: 'Small dark glass bubble', motion: 'Slow drift, own speed', mobile: 'Optional' },
      { name: 'bubble-dark-04', at: [1560, 390], mode: 'Dark', role: 'Medium dark glass bubble', motion: 'Slow drift, own speed', mobile: 'Optional' },
      { name: 'swoosh-light-01', at: [235, 560], mode: 'Light', role: 'Large liquid-glass arc, for a corner', motion: 'Very slow rotate (±3–4deg) and scale (≤1.05), 70–100s', mobile: 'Keep, cropped by the corner' },
      { name: 'swoosh-light-02', at: [640, 545], mode: 'Light', role: 'Liquid-glass arc with a curled tail', motion: 'Very slow rotate and scale, own clock', mobile: 'Optional' },
      { name: 'swoosh-dark-01', at: [1050, 560], mode: 'Dark', role: 'Large dark liquid-glass arc with amber light', motion: 'Very slow rotate and scale, 70–100s', mobile: 'Keep, cropped by the corner' },
      { name: 'swoosh-dark-02', at: [1450, 540], mode: 'Dark', role: 'Dark liquid-glass arc with a curled tail', motion: 'Very slow rotate and scale, own clock', mobile: 'Optional' },
      { name: 'wave-light-01', at: [160, 700], mode: 'Light', role: 'Small liquid-glass wave', motion: 'Slow drift and a few degrees of turn, 40–70s', mobile: 'Optional' },
      { name: 'wave-light-02', at: [450, 690], mode: 'Light', role: 'Liquid-glass ribbon', motion: 'Slow drift and turn, own clock', mobile: 'Optional' },
      { name: 'wave-light-03', at: [715, 695], mode: 'Light', role: 'Liquid-glass wave with a curl', motion: 'Slow drift and turn, own clock', mobile: 'Optional' },
      { name: 'wave-dark-01', at: [1000, 700], mode: 'Dark', role: 'Small dark liquid-glass wave', motion: 'Slow drift and turn, 40–70s', mobile: 'Optional' },
      { name: 'wave-dark-02', at: [1280, 710], mode: 'Dark', role: 'Dark liquid-glass ribbon', motion: 'Slow drift and turn, own clock', mobile: 'Optional' },
      { name: 'wave-dark-03', at: [1530, 700], mode: 'Dark', role: 'Dark liquid-glass wave with a curl', motion: 'Slow drift and turn, own clock', mobile: 'Optional' },
      { name: 'caustics-light-cool', at: [220, 850], mode: 'Light', role: 'Soft pool of cool water caustics, light travelling over the page', motion: 'Slow translate across an edge (5–9vw over 60–80s) with an opacity breathe', mobile: 'Optional' },
      { name: 'caustics-light-warm', at: [618, 850], mode: 'Light', role: 'Pool of warm (amber) water caustics', motion: 'As above, own clock', mobile: 'Optional' },
      { name: 'caustics-dark-cool', at: [1055, 850], mode: 'Dark', role: 'Pool of blue water caustics', motion: 'As above, own clock', mobile: 'Optional' },
      { name: 'caustics-dark-warm', at: [1465, 850], mode: 'Dark', role: 'Pool of amber water caustics', motion: 'As above, own clock', mobile: 'Optional' }
    ]
  }
};
